# Generated by Django 3.2.16 on 2023-10-02 15:00

from django.db import migrations, models
import django.db.models.deletion
import startupapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientsLogos', models.ImageField(upload_to=startupapp.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Address', max_length=5000)),
                ('emails', models.CharField(default='Emails', max_length=2000)),
                ('phone', models.CharField(default='Phone', max_length=2000)),
                ('openHours', models.CharField(default='OpenHours', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=2000)),
                ('emails', models.CharField(default='Emails', max_length=2000)),
                ('subject', models.CharField(default='Subject', max_length=2000)),
                ('message', models.CharField(default='message', max_length=10000)),
                ('sendtoEmail', models.CharField(default='Send To Email', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=startupapp.models.upload_to)),
                ('heroTitle', models.CharField(default='heroTitle', max_length=10000)),
                ('heroSubTitle', models.CharField(default='heroSubTitle', max_length=10000)),
                ('heroButtonText', models.CharField(default='heroButtonText', max_length=10000)),
                ('heroButtonLink', models.CharField(default='heroButtonLink', max_length=10000)),
                ('heroImage', models.ImageField(upload_to=startupapp.models.upload_to)),
                ('aboutHeader', models.CharField(default='aboutHeader', max_length=10000)),
                ('aboutTitle', models.CharField(default='aboutTitle', max_length=10000)),
                ('aboutSubTitle', models.CharField(default='aboutSubTitle', max_length=10000)),
                ('aboutButtonText', models.CharField(default='aboutButtonText', max_length=10000)),
                ('aboutButtonLink', models.CharField(default='aboutButtonLink', max_length=10000)),
                ('aboutImage', models.ImageField(upload_to=startupapp.models.upload_to)),
                ('valueHeader', models.CharField(default='valueHeader', max_length=10000)),
                ('valueTitle', models.CharField(default='valueTitle', max_length=10000)),
                ('value1Title', models.CharField(default='value1Title', max_length=10000)),
                ('value1Description', models.TextField(default='Value1Description')),
                ('value1Image', models.ImageField(upload_to=startupapp.models.upload_to)),
                ('value2Title', models.CharField(default='value2Title', max_length=10000)),
                ('value2Description', models.TextField(default='Value2Description')),
                ('value2Image', models.ImageField(upload_to=startupapp.models.upload_to)),
                ('value3Title', models.CharField(default='value2Title', max_length=10000)),
                ('value3Description', models.TextField(default='Value3Description')),
                ('value3Image', models.ImageField(upload_to=startupapp.models.upload_to)),
                ('clientCounter', models.IntegerField(default=1)),
                ('projectCounter', models.IntegerField(default=1)),
                ('hourCounter', models.IntegerField(default=1)),
                ('hardWorkerCounter', models.IntegerField(default=1)),
                ('serviceHeader', models.CharField(default='ServiceHeader', max_length=500)),
                ('serviceTItle', models.CharField(default='ServiceTitle', max_length=1000)),
                ('footerLogo', models.ImageField(upload_to=startupapp.models.upload_to)),
                ('footerTitle', models.CharField(default='Footer Details', max_length=10000)),
                ('facebook', models.CharField(default='https://facebook.com/iamsheikhtabarak', max_length=2000)),
                ('instagram', models.CharField(default='https://instagram.com/sheikh_tabarak', max_length=2000)),
                ('linkedin', models.CharField(default='https://linkedin.com/in/sheikhtabarak', max_length=2000)),
                ('fiverr', models.CharField(default='https://fiverr.com/sheikhtabarak', max_length=2000)),
                ('upwork', models.CharField(default='https://upwork.com/user/sheikhtabarak', max_length=2000)),
                ('copyright', models.CharField(default='hCopyrights 2023 TrioCodex', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='FAQs Questions', max_length=2000)),
                ('answer', models.CharField(default='FAQs Answer', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=1000)),
                ('description', models.TextField(default='Description')),
                ('icon', models.CharField(default='ri-discuss-line icon', max_length=500)),
                ('buttonText', models.CharField(default='', max_length=10000)),
                ('buttonLink', models.CharField(default='blue', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(upload_to=startupapp.models.upload_to)),
                ('name', models.CharField(default='Name Team', max_length=2000)),
                ('designation', models.CharField(default=' Description Name', max_length=2000)),
                ('description', models.CharField(default='Description Team', max_length=10000)),
                ('facebook', models.CharField(default='https://facebook.com/iamsheikhtabarak', max_length=2000)),
                ('instagram', models.CharField(default='https://instagram.com/sheikh_tabarak', max_length=2000)),
                ('linkedin', models.CharField(default='https://linkedin.com/in/sheikhtabarak', max_length=2000)),
                ('fiverr', models.CharField(default='https://fiverr.com/sheikhtabarak', max_length=2000)),
                ('upwork', models.CharField(default='https://upwork.com/user/sheikhtabarak', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonialImage', models.ImageField(upload_to=startupapp.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ImageField(upload_to=startupapp.models.upload_to)),
                ('name', models.CharField(default='Project Team', max_length=10000)),
                ('description', models.CharField(default='Project Description', max_length=10000)),
                ('projectLink', models.CharField(default='Project Link', max_length=10000)),
                ('projectGithub', models.CharField(default='Project Guthub', max_length=10000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupapp.service')),
            ],
        ),
    ]
