# Generated by Django 3.2.16 on 2023-10-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetails',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='buttonLink',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='sendtoEmail',
        ),
        migrations.AddField(
            model_name='content',
            name='address',
            field=models.CharField(default='GUjranwala', max_length=5000),
        ),
        migrations.AddField(
            model_name='content',
            name='emails',
            field=models.CharField(default='tricodex@gmail.com', max_length=2000),
        ),
        migrations.AddField(
            model_name='content',
            name='openHours',
            field=models.CharField(default='Monday - Friday<br>9:00AM - 5:00PM', max_length=5000),
        ),
        migrations.AddField(
            model_name='content',
            name='phone',
            field=models.CharField(default='xxxx-xxxxxxx', max_length=2000),
        ),
        migrations.AddField(
            model_name='service',
            name='bicon',
            field=models.CharField(default='ri-discuss-line icon', max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='copyright',
            field=models.CharField(default='Copyrights 2023 TrioCodex', max_length=5000),
        ),
    ]
